config/routes.rb
Rails.application.routes.draw do
  # resources
  resources :articles, only: [:show] do
    resources :sentiments, only: [:index]
  end

  #routes for saved/favorited articles
  resources :favorites, controller: 'articles'

  resources :users
  resources :sessions, only: [:create, :destroy]
  resources :password_resets, except: [:destroy]

  root "welcome#index"

  ## CUSTOM ROUTES ##
  # password reset routes
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'

  # session routes

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  # users routes
  get "signup" => "users#new", :as => "signup"


  # articles routes
  get "/search" => "articles#search"  # search results

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :favorites

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def not_authenticated
    redirect_to login_url, :alert => "First login to access this page."
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
  end

  def search
    @keyword = params[:article][:name]
    nyt_response = call_NYT_API q: @keyword

    if nyt_response
      # Grabs the headline and ID from each article search result
      @results = nyt_response.map do |article|
        { id: article["_id"],
          headline: article["headline"]["main"] }
      end
    end
  end

  def show
    #if id params has letters in it, it is NYTimes ID (not persisted) and new Favorite
    if (/[A-z]/) =~ params[:id]
      nyt_id = params[:id]
      @favorite = Favorite.new

    else #if id params doesn't have letters in it, it is Trend365 ID (is persisted) and existing Favorite
      @favorited = true
      @favorite = Favorite.find(params[:id])
      nyt_id = @favorite.nyt_id
    end

    #grab info from API regardless, using nyt_id from conditional
    nyt_response = call_NYT_API(fq: "_id:(\"#{nyt_id}\")")[0]

    if nyt_response
      @result = {
        :headline => nyt_response["headline"]["main"],
        :snippet  => nyt_response["snippet"],
        :url      => nyt_response["web_url"],
        :date     => nyt_response["pub_date"].to_s[0..9]
      }
    end
  end

  def create
    # params coming from hidden fields in "save" form/button
    @favorite = Favorite.create({
      nyt_id: params[:nyt_id],
      title: params[:title],
      user_id: params[:user_id]
    })
    redirect_to favorite_path(@favorite)
  end


  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to root_path
  end

  private
  # Calls the NYT API, expects a hash of options that correspond to NYT API params
  # http://developer.nytimes.com/docs/read/article_search_api_v2
  def call_NYT_API(options = {})
    # Build request URL for NYT API
    base_url = "http://api.nytimes.com/svc/search/v2/articlesearch.json"
    params = { :"api-key" => Rails.application.secrets[:nyt_api_key] }
    params.merge! options
    request_url = [base_url, params.to_query].join("?")

    # Get results
    results = HTTParty.get request_url

    # Check if there are any results returned & return them
    # Otherwise, return nil if there are no results
    %w( response docs ).reduce(results) do |data, key|
      return nil unless data[key]
      data = data[key]
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create
    @user = User.find_by_email(params[:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end

  # This is the reset password form.
  def edit
    @user = User.load_from_reset_password_token(params[:id])
    @token = params[:id]

    if @user.blank?
      not_authenticated
      return
    end
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = params[:token]
    @user = User.load_from_reset_password_token(params[:token])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/sentiments_controller.rb
class SentimentsController < ApplicationController
  def index
    # Get sentiment from AlchemyAPI for the specified URL
    api = AlchemyAPI.new params[:url]
    @keywords = api.extract_keyword_sentiment

    # Return keyword sentiment data as JSON
    if @keywords
      render json: @keywords
    else
      head :bad_request
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
  user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_back_or_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      auto_login(@user)
      redirect_to root_url, :notice => "Signed up!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation
      )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
    @favorites = Favorite.where(user_id: current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/search.html.erb
<h2>Search Results</h2>
  <ul>
    <% if @results %>
      <% @results.each do |article| %>
        <li>
          <%= link_to article[:headline], article_path(article[:id]) %>
        </li>
      <% end %>
    <% else %>
      <p>No results found.</p>
    <% end %>
  </ul>

app/views/articles/show.html.erb
<%= javascript_include_tag "articles" %>
<% if @favorited %>
&hearts;
<% end %>
<a href="<%= @result[:url] %>" class="h1"><%= @result[:headline] %></a>
<%= content_tag :p, @result[:date] %>
<%= content_tag :h5, @result[:snippet] %>

<% if current_user %>

  <% if !@favorited %>
    <%= form_for @favorite do |f|%>
      <%= hidden_field_tag :title, @result[:headline] %>
      <%= hidden_field_tag :user_id, current_user.id %>
      <%= hidden_field_tag :nyt_id, params[:id] %>
      <%= f.submit "Save Article to Favorites" %>
    <% end %>
  <% else %>
    <%= form_for @favorite, method: 'delete' do |f|%>
      <%= f.submit "Delete Article from Favorites" %>
    <% end %>
  <% end %>

  <hr>

  <a href= "mailto: ?subject=<%= @result[:headline] %>&body=Checkout This Rad Article I found on Trend365:  <%= @result[:url] %>" class= "btn btn-default" >Email to a friend</a>

<% end %>

<%= content_tag :div, id: "chart", data: { url: @result[:url] } do %>
  <svg class="svg-bar-chart"></svg>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trend365</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "d3.min" %>
  <%= javascript_include_tag "nv.d3.min" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- NAVIGATION -->

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Trend.365</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/search">YEAR TREND</a></li>
      </ul>
      <%= form_tag search_path, class: "navbar-form navbar-left", role: "search", method: "get" do %>
        <div class="form-group">
          <%= text_field :article, :name, placeholder: "Search", class: "form-control" %>
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      <% end %>
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <% if current_user %>
            <!--Logged in as <%= current_user.email %>-->
          <a href="<%= edit_user_path(current_user) %>" class="btn btn-default">
            Edit Your Account
          </a>
          <a href="<%= logout_path %>" class="btn btn-default">
            Log Out
          </a>
          <% else %>
          <a href="<%= signup_path %>" class="btn btn-default" >
            Sign Up
          </a>
          <a href="<%= login_path %>" class="btn btn-default" >
            Sign In
          </a>
          <% end %>
        </div>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!-- END NAVIGATION -->





<%= yield %>
<div class="footer">
  <%= link_to "Text Analysis by AlchemyAPI", "http://www.alchemyapi.com/" %>
</div>
</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@user), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
    <%= hidden_field_tag :token, @token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user_form.html.erb
<div class="user_details">
  <%= bootstrap_form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <%= f.email_field :email %>
      <%= f.password_field :password %>
      <%= f.password_field :password_confirmation %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/edit.html.erb
  <h1 class="user_details">Edit User Information</h1>

  <%= render 'user_form' %>

app/views/users/new.html.erb
  <h1 class="user_details">New User Sign Up</h1>

  <%= render 'user_form' %>

app/views/welcome/index.html.erb
<h1 class="user_details">Trend365</h1>
<% if current_user %>
  <h2>Favorites</h2>
  <ul>
    <% @favorites.each do |favorite| %>
      <li>
        <%= link_to favorite.title, favorite_path(favorite) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="jumbotron">
    <h2>The Story <i>Is</i> The Story</h2>
    <p>Does the media play favorites?  Is it liberal?  Conservative?  Are journalists coddling leaders they should be holding accountable?</p>
    <p>Trend365 offers you unprecedented article-by-article analysis answering just these questions.
    We've parsed the news and brought underlying sentiment to light, representing positive and negative coverage with vibrant bar graphs.</p>
    <p>Are topics you care about getting a fair shake?  See for yourself.</p>
    <p><a class="btn btn-primary btn-lg" role="button">Learn more</a></p>


  </div>
<% end %>